version: "3.3"
services:
  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: poll
    ports:
      ["3306:3306"]
    volumes:
      ["./mariadb.conf:/etc/mysql/conf.d/config-file.cnf", "./db/data:/var/lib/mysql:rw"]

  flask:
    links:
     - mariadb
    ports:
      ["5000:5000"]
    build:
      context: ./flask
      dockerfile: Dockerfile.test
