version: '3'

services:
  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: limon
    ports:
      ["3333:3333"]
    volumes:
      ["./mariadb.conf:/etc/mysql/conf.d/config-file.cnf", "./db/data:/var/lib/mysql:rw"]

  flask_web:
    build: ./flask
    ports: ["5000:5000"]
