version: '1'

services:
  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: limon
    ports:
      -"3333:3322"
    volumes:
      -"./mariadb.conf:/etc/mysql/conf.d/config-file.cnf"
      -"./data:/var/lib/mysql:rw"

  flask:
    build: ./flask
    ports: "8080:8080"
