version: '3'

services:
  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: poll
    networks:
     - appnet
     ports:
      ["3306:3306"]
    volumes:
      ["./db/mariadb.conf:/etc/mysql/conf.d/config-file.cnf", "./db/data:/var/lib/mysql:rw"]

  flask:
    networks:
     - appnet
    build: ./flask
    ports: ["5000:5000"]
    links:
      - mariadb

networks:
  appnet:
