version: '3'

services:
  mariadb:
    image: mariadb:latest
    dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: limon
    ports:
      ["3333:3333"]
    volumes:
      ["./mariadb.conf:/etc/mysql/conf.d/config-file.cnf", "./db/data:/var/lib/mysql:rw"]
    
  flask:
    dockerfile: Dockerfile.test
    build: ./flask
    ports: ["5000:5000"]
    add: tests.sh /flask
